-- 299: Зарплата — справочник видов удержаний и вид удержания в условиях оплаты.
--
-- Зачем. Вкладка «Расчёты» показывает сотрудников с удержаниями: строки — сотрудники,
-- столбцы — виды из справочника. Удержание задаётся в карточке «Зарплата → Подробно»:
-- «Вид» из справочника и «Сумма, ₽/мес» (deduction_amount, миграция 286) сохраняются
-- вместе, в версии условий оплаты.
--
-- Справочник пополняется на вкладке «Расчёты» (кнопка «Добавить вид»); правки и удаления
-- видов нет. Стартовые виды — из выгрузки ЗУП: Корректировка удержаний, ТМЦ, Штраф за мусор,
-- Спецодежда, Питание, Штрафы. Автора вида не храним — добавление пишется в аудит.
--
-- Данных переносить не нужно: на момент миграции условий с удержанием нет.
--
-- ПРИМЕНЯТЬ ДО ДЕПЛОЯ БЭКЕНДА. Повторный запуск безопасен.

BEGIN;

CREATE TABLE IF NOT EXISTS payroll_deduction_kinds (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 1000,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT payroll_deduction_kind_name CHECK (btrim(name) <> '' AND length(name) <= 100)
);

-- Без учёта регистра и пробелов по краям: «Штрафы» и « штрафы» — один вид.
CREATE UNIQUE INDEX IF NOT EXISTS payroll_deduction_kinds_name_uniq
  ON payroll_deduction_kinds (lower(btrim(name)));

INSERT INTO payroll_deduction_kinds (name, sort_order) VALUES
  ('Корректировка удержаний', 10),
  ('ТМЦ',                     20),
  ('Штраф за мусор',          30),
  ('Спецодежда',              40),
  ('Питание',                 50),
  ('Штрафы',                  60)
ON CONFLICT DO NOTHING;

COMMENT ON TABLE payroll_deduction_kinds IS
  'Справочник видов удержаний («Зарплата → Расчёты»). Пополняется пользователями, не удаляется.';

ALTER TABLE payroll_compensation_terms
  ADD COLUMN IF NOT EXISTS deduction_kind_id INTEGER
    REFERENCES payroll_deduction_kinds(id) ON DELETE RESTRICT;

ALTER TABLE payroll_compensation_terms DROP CONSTRAINT IF EXISTS payroll_terms_deduction_pair;
ALTER TABLE payroll_compensation_terms ADD CONSTRAINT payroll_terms_deduction_pair
  CHECK ((deduction_kind_id IS NULL) = (deduction_amount IS NULL));

COMMENT ON COLUMN payroll_compensation_terms.deduction_kind_id IS
  'Вид удержания из payroll_deduction_kinds; задаётся вместе с deduction_amount.';

REVOKE ALL ON TABLE public.payroll_deduction_kinds FROM PUBLIC;

COMMIT;
