-- 303: Зарплата — удержания сотрудника по месяцам: месяц · вид · сумма.
--
-- Зачем. Вкладка «Расчёты» показывает весь штат; клик по сотруднику открывает его карточку
-- в окне, и там вносятся удержания строками «месяц · вид из справочника (299) · сумма».
-- Фильтр «Удержания» + месяц на «Расчётах» оставляет сотрудников, у кого отмеченный вид есть
-- за выбранный месяц, и показывает их сумму.
--
-- Заменяет виды сотрудника без месяца (payroll_employee_deductions, миграция 300) и сумму
-- удержания ₽/мес в условиях оплаты (deduction_amount, 286). Данных переносить не нужно: на
-- момент миграции ни условий, ни отмеченных видов нет. Прежние таблица и колонки остаются —
-- их читает прежний бэкенд; удалить отдельной миграцией после деплоя.
--
-- Один вид за месяц — одна строка (сумма за месяц). Автора не храним (без FK на пользователя) —
-- изменения пишутся в аудит.
--
-- ПРИМЕНЯТЬ ДО ДЕПЛОЯ БЭКЕНДА. Прежний бэкенд с ней работает. Повторный запуск безопасен.

BEGIN;

CREATE TABLE IF NOT EXISTS payroll_deduction_entries (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  kind_id     INTEGER NOT NULL REFERENCES payroll_deduction_kinds(id) ON DELETE RESTRICT,
  month       DATE NOT NULL,
  amount      NUMERIC(12,2) NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT payroll_deduction_entries_month CHECK (month = date_trunc('month', month)::date),
  CONSTRAINT payroll_deduction_entries_amount CHECK (amount > 0),
  CONSTRAINT payroll_deduction_entries_uniq UNIQUE (employee_id, month, kind_id)
);

-- Фильтр «Расчётов»: вид(ы) за месяц.
CREATE INDEX IF NOT EXISTS payroll_deduction_entries_month_kind_idx
  ON payroll_deduction_entries (month, kind_id);

COMMENT ON TABLE payroll_deduction_entries IS
  'Удержания сотрудника по месяцам («Зарплата → Расчёты», карточка «Подробно»): месяц (1-е число), вид, сумма.';

COMMENT ON TABLE payroll_employee_deductions IS
  'Не используется с миграции 303 (удержания по месяцам — payroll_deduction_entries); удалить отдельной миграцией.';

REVOKE ALL ON TABLE public.payroll_deduction_entries FROM PUBLIC;

COMMIT;
